spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://3.34.xxx.xxx:5432/recorddb
    username: recorduser
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
