spring:
  profiles:
    active: dev   # 기본 실행 프로필을 dev로 활성화

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

openai:
  api:
    key: ${OPENAI_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: ap-northeast-2
    s3:
      bucket: recording-bucket

stt:
  ffmpeg:
    path: ${FFMPEG_PATH:ffmpeg}
